# Generated by Django 4.2.3 on 2023-09-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adress_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='adress_line_2',
            new_name='address_line_2',
        ),
    ]
